<link rel="stylesheet" href="${pageContext.request.contextPath}/assets/css/bootstrap.min.css">
<link rel="stylesheet" href="${pageContext.request.contextPath}/assets/css/all.min.css">
<link rel="stylesheet" href="${pageContext.request.contextPath}/assets/css/main.css">
<link rel="stylesheet" href="${pageContext.request.contextPath}/assets/css/noty.css">
<script src="${pageContext.request.contextPath}/assets/js/jquery-3.5.0.min.js" ></script>
<script src="${pageContext.request.contextPath}/assets/js/bootstrap.min.js" ></script>
<script src="${pageContext.request.contextPath}/assets/js/all.min.js" ></script>
<script src="${pageContext.request.contextPath}/assets/js/Chart.min.js" ></script>
<script src="${pageContext.request.contextPath}/assets/js/noty.min.js" ></script>
